package dev.yjyoon.alreadyme.data.exception

object CommonException {
    val message = mapOf(400 to "Invalid Github URL", 500 to "Internal Server Error")
}
